'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const frontendRoot = path.resolve(__dirname, '..')
const pagePath = path.join(frontendRoot, 'src/app/(dashboard)/cmdb/admin/models/[modelCode]/page.tsx')
const listPath = path.join(frontendRoot, 'src/app/(dashboard)/cmdb/admin/models/[modelCode]/components/AttributeList.tsx')
const addDialogPath = path.join(frontendRoot, 'src/app/(dashboard)/cmdb/admin/models/[modelCode]/components/AddAttributeDialog.tsx')
const editDialogPath = path.join(frontendRoot, 'src/app/(dashboard)/cmdb/admin/models/[modelCode]/components/EditAttributeDialog.tsx')
const patternsPath = path.join(frontendRoot, 'src/design-system/figma-neutral/components/patterns.css')

test('cmdb model detail follows the overview density baseline', () => {
  const page = fs.readFileSync(pagePath, 'utf8')
  const list = fs.readFileSync(listPath, 'utf8')
  const addDialog = fs.readFileSync(addDialogPath, 'utf8')
  const editDialog = fs.readFileSync(editDialogPath, 'utf8')
  const patterns = fs.readFileSync(patternsPath, 'utf8')

  assert.match(page, /cwgsyw-cmdb-page cwgsyw-cmdb-admin cwgsyw-cmdb-model-detail/)
  assert.match(page, /cwgsyw-cmdb-overview__catalog-note/)
  assert.match(page, /Icon name="chevron-next"/)
  assert.match(page, /Icon name="chevron-previous"/)
  assert.doesNotMatch(page, /<Breadcrumb/)
  assert.match(page, /<Button type="button" size="sm"/)

  assert.match(list, /<Table/)
  assert.match(list, /showSearch=\{false\}/)
  assert.match(list, /label: '属性名称'/)
  assert.match(list, /label: '字段标识'/)
  assert.match(list, /label: '类型'/)
  assert.match(list, /label: '配置'/)
  assert.match(list, /label: '', align: 'right'/)
  assert.match(list, /<CmdbAdminActionIcon name="edit"/)
  assert.match(list, /<CmdbAdminActionIcon name="trash"/)
  assert.match(list, /disabled=\{attr\.isBuiltIn\}/)
  assert.doesNotMatch(list, /<Card/)
  assert.doesNotMatch(list, /<Chip/)
  assert.doesNotMatch(list, />\s*编辑\s*</)
  assert.doesNotMatch(list, />\s*删除\s*</)

  assert.match(addDialog, /cwgsyw-cmdb-model-detail__dialog-flags/)
  assert.match(editDialog, /cwgsyw-cmdb-model-detail__dialog-flags/)
  assert.match(addDialog, /variant="ghost" size="sm"/)
  assert.match(editDialog, /variant="ghost" size="sm"/)

  assert.match(patterns, /\.cwgsyw-cmdb-model-detail__groups[\s\S]*gap: var\(--cwgsyw-space-6\)/)
  assert.match(patterns, /\.cwgsyw-cmdb-model-detail__group-title[\s\S]*font-weight: var\(--cwgsyw-font-weight-regular\)/)
  assert.match(patterns, /\.cwgsyw-dialog:has\(\.cwgsyw-cmdb-model-detail__dialog-form\)[\s\S]*padding: var\(--cwgsyw-space-4\)/)
  assert.match(patterns, /cwgsyw-dialog__title-group \.cwgsyw-type-title-sm[\s\S]*font-size: 16px[\s\S]*font-weight: var\(--cwgsyw-font-weight-medium\)/)
  assert.match(patterns, /cwgsyw-dialog__body[\s\S]*padding: 0[\s\S]*background: var\(--cwgsyw-bg-surface\)/)
  assert.match(patterns, /\.cwgsyw-cmdb-model-detail__dialog-form \.cwgsyw-filter-grid[\s\S]*repeat\(2, minmax\(0, 1fr\)\)/)
  assert.match(patterns, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);[\s\S]*align-items: start/)
  assert.match(patterns, /\.cwgsyw-cmdb-model-detail__dialog-form \.cwgsyw-field[\s\S]*align-content: start[\s\S]*padding: 0/)
  assert.match(patterns, /cwgsyw-cmdb-model-detail__dialog-form :where\([\s\S]*font-size: var\(--cwgsyw-font-size-label-sm\)/)
  assert.match(patterns, /cwgsyw-field__label-row \.cwgsyw-type-label-sm[\s\S]*font-weight: var\(--cwgsyw-font-weight-regular\)/)
  assert.match(patterns, /\.cwgsyw-cmdb-model-detail__dialog-form \.cwgsyw-field__required[\s\S]*font-size: var\(--cwgsyw-font-size-label-sm\)[\s\S]*line-height: var\(--cwgsyw-type-label-sm-line-height\)/)
  assert.match(patterns, /\.cwgsyw-cmdb-model-detail__dialog-form \.cwgsyw-choice input[\s\S]*width: 16px[\s\S]*height: 16px/)
  assert.match(patterns, /\.cwgsyw-cmdb-model-detail__dialog-flags[\s\S]*flex-wrap: wrap/)
})
