'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const files = [
  'src/components/layout/Header.tsx',
  'src/components/layout/sidebar/NavGroupItem.tsx',
  'src/components/layout/sidebar/CollapsedEntry.tsx',
]

test('app header and sidebar chrome use Neutral controls without redundant header actions', () => {
  for (const rel of files) {
    const source = fs.readFileSync(path.resolve(__dirname, '..', rel), 'utf8')
    assert.doesNotMatch(source, /<button[\s>]/, rel)
  }
  const header = fs.readFileSync(path.resolve(__dirname, '../src/components/layout/Header.tsx'), 'utf8')
  const sidebar = fs.readFileSync(path.resolve(__dirname, '../src/components/layout/Sidebar.tsx'), 'utf8')
  const logo = fs.readFileSync(path.resolve(__dirname, '../public/sidebar-logo.png'))
  const userChevron = fs.readFileSync(path.resolve(__dirname, '../public/figma-icons/sidebar-chevrons-up-down.svg'), 'utf8')
  assert.match(sidebar, /MenuItem/)
  assert.match(sidebar, /aria-label="打开用户菜单"/)
  assert.match(sidebar, /data-figma-node="2:7746"/)
  assert.match(sidebar, /AnimatePresence initial=\{false\}/)
  assert.match(sidebar, /initial=\{reduceMotion \? \{ opacity: 0 \} : \{ opacity: 0, y: 8, scale: 0\.97 \}\}/)
  assert.match(sidebar, /document\.addEventListener\('pointerdown', closeOnOutsidePointer\)/)
  assert.match(sidebar, /document\.addEventListener\('keydown', closeOnEscape\)/)
  assert.match(sidebar, /cwgsyw-sidebar__user-copy/)
  assert.match(sidebar, /cwgsyw-sidebar__user-avatar/)
  assert.match(sidebar, /size="md"/)
  assert.match(sidebar, /Array\.from\(fallbackName\)\[0\]\?\.toUpperCase\(\)/)
  assert.match(sidebar, /user\?\.realName \|\| user\?\.username \|\| '-'/)
  assert.match(sidebar, /\/figma-icons\/sidebar-chevrons-up-down\.svg/)
  assert.match(userChevron, /viewBox="0 0 8 12"/)
  assert.match(userChevron, /id="Union"/)
  assert.match(sidebar, /SIDEBAR_LOGO_URL = '\/sidebar-logo\.png'/)
  assert.equal(logo.subarray(0, 8).toString('hex'), '89504e470d0a1a0a')
  assert.match(header, /NotificationBell/)
  assert.match(header, /cwgsyw-app-header__actions/)
  assert.match(header, /setTheme\(isDark \? 'light' : 'dark'\)/)
  assert.doesNotMatch(header, /搜索/)
  assert.doesNotMatch(header, /新建变更/)
  const patterns = fs.readFileSync(path.resolve(__dirname, '../src/design-system/figma-neutral/components/patterns.css'), 'utf8')
  const appHeaderRules = patterns.slice(patterns.indexOf('.cwgsyw-app-header {'), patterns.indexOf('.cwgsyw-app-header__context'))
  assert.match(patterns, /html:has\(\.cwgsyw-app-shell\),[\s\S]*?body:has\(\.cwgsyw-app-shell\)\s*\{[\s\S]*?height:\s*100%;[\s\S]*?overflow:\s*hidden;/)
  assert.match(patterns, /\.cwgsyw-app-shell\s*\{[\s\S]*?width:\s*100%;[\s\S]*?max-width:\s*100%;[\s\S]*?height:\s*100dvh;/)
  assert.doesNotMatch(appHeaderRules, /border-bottom/)
  assert.match(patterns, /navbar-theme-sun\.svg/)
  assert.match(patterns, /navbar-theme-moon\.svg/)
  assert.match(patterns, /\.cwgsyw-app-header__figma-icon,[\s\S]*?\.cwgsyw-notification-bell__icon\s*\{[\s\S]*?width:\s*18px;[\s\S]*?height:\s*18px;/)
  assert.match(patterns, /\.cwgsyw-app-header \.cwgsyw-app-header__theme-toggle\.cwgsyw-icon-btn,[\s\S]*?\.cwgsyw-app-header \.cwgsyw-notification-bell\s*\{[\s\S]*?width:\s*24px;[\s\S]*?height:\s*24px;[\s\S]*?background:\s*transparent;[\s\S]*?box-shadow:\s*none;/)
  assert.match(patterns, /\.cwgsyw-app-header \.cwgsyw-app-header__theme-toggle\.cwgsyw-icon-btn--ghost:hover:not\(:disabled\):not\(\[aria-busy="true"\]\),[\s\S]*?background:\s*transparent;/)
  assert.match(patterns, /backdrop-filter: blur\(16px\)/)
  assert.match(patterns, /mask-image: linear-gradient\(to bottom/)
  assert.match(patterns, /inset: 0 0 -60px/)
  assert.match(patterns, /\.cwgsyw-sidebar__brand\s*\{[\s\S]*?align-items:\s*flex-end;/)
  assert.match(patterns, /\.cwgsyw-sidebar__logomark\s*\{[\s\S]*?width:\s*48px;[\s\S]*?height:\s*48px;/)
  assert.match(patterns, /\.cwgsyw-sidebar--collapsed \.cwgsyw-sidebar__brand\s*\{[\s\S]*?padding-inline:\s*4px;/)
  assert.match(patterns, /\.cwgsyw-sidebar--collapsed \.cwgsyw-sidebar__logomark\s*\{[\s\S]*?width:\s*32px;[\s\S]*?height:\s*32px;/)
  assert.match(patterns, /\.cwgsyw-sidebar \.cwgsyw-sidebar__user-trigger\.cwgsyw-icon-btn\s*\{[\s\S]*?width:\s*100%;[\s\S]*?justify-content:\s*flex-start;/)
  assert.match(patterns, /\.cwgsyw-sidebar__user-avatar\s*\{[\s\S]*?width:\s*32px;[\s\S]*?height:\s*32px;/)
  assert.match(patterns, /\.cwgsyw-sidebar__user-avatar\.is-fallback \.cwgsyw-avatar\s*\{[\s\S]*?background:\s*var\(--cwgsyw-neutral-900\);[\s\S]*?color:\s*var\(--cwgsyw-neutral-100\);[\s\S]*?font-weight:\s*var\(--cwgsyw-font-weight-bold\);/)
  assert.match(patterns, /\.cwgsyw-sidebar-user-menu\s*\{[\s\S]*?border-radius:\s*var\(--cwgsyw-radius-xl\);[\s\S]*?transform-origin:\s*left bottom;/)
})
