'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Archive, Building2, FilePlus2, Map, RotateCcw, Search } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { getApiErrorMessage } from '@/lib/api-error'
import { archiveSpatialLayout, createSpatialLayout, listSpatialLayouts, listSpatialRooms, restoreActiveSpatialLayout, spatialQueryKeys } from '../api/spatial-api'
import type { SpatialLayoutSummary } from '../model/types'

interface SpatialLayoutIndexProps { canCreate: boolean; canPublish: boolean }

export function SpatialLayoutIndex({ canCreate, canPublish }: SpatialLayoutIndexProps) {
  const client = useQueryClient(); const [keyword, setKeyword] = useState(''); const [showCreate, setShowCreate] = useState(false); const [roomId, setRoomId] = useState(''); const [includeArchived, setIncludeArchived] = useState(false); const [archiving, setArchiving] = useState<SpatialLayoutSummary | null>(null); const [restoring, setRestoring] = useState<SpatialLayoutSummary | null>(null)
  const { data: layouts = [], isLoading, isError, error } = useQuery({ queryKey: spatialQueryKeys.layouts(includeArchived), queryFn: () => listSpatialLayouts(includeArchived) })
  const { data: rooms = [] } = useQuery({ queryKey: spatialQueryKeys.rooms('', false), queryFn: () => listSpatialRooms('', false), enabled: canCreate })
  const invalidateLayoutAvailability = () => {
    client.invalidateQueries({ queryKey: ['cmdb', 'spatial', 'layouts'] })
    client.invalidateQueries({ queryKey: ['cmdb', 'spatial', 'rooms'] })
  }
  const create = useMutation({ mutationFn: () => createSpatialLayout(Number(roomId), `${rooms.find((room) => room.roomInstanceId === Number(roomId))?.name || '机房'}逻辑布局`), onSuccess: (layout) => { invalidateLayoutAvailability(); window.location.assign(`/cmdb/spatial/rooms/${layout.roomInstanceId}/edit`) } })
  const archive = useMutation({ mutationFn: (layoutId: number) => archiveSpatialLayout(layoutId), onSuccess: () => { setArchiving(null); invalidateLayoutAvailability() } })
  const restore = useMutation({ mutationFn: (layoutId: number) => restoreActiveSpatialLayout(layoutId), onSuccess: () => { setRestoring(null); invalidateLayoutAvailability() } })
  const visible = useMemo(() => layouts.filter((layout) => layout.status === (includeArchived ? 'ARCHIVED' : 'ACTIVE') && layout.name.includes(keyword)), [includeArchived, keyword, layouts])
  const availableRooms = rooms.filter((room) => !room.configured)
  if (isLoading) return <div className="py-24 text-center text-sm text-v2-muted">正在加载空间布局...</div>
  if (isError) return <div className="py-24 text-center text-sm text-v2-danger">{getApiErrorMessage(error, '空间布局加载失败')}</div>
  return <div className="max-w-6xl space-y-5">
    <div className="flex flex-wrap items-center gap-3 border-b border-v2-border pb-4"><div className="min-w-48 flex-1"><h1 className="text-xl font-semibold text-v2-fg">空间布局</h1><p className="mt-1 text-sm text-v2-muted">机房、机柜与 CI 的二维位置视图</p></div><div className="flex rounded-v2-sm border border-v2-border p-0.5"><button onClick={() => setIncludeArchived(false)} className={!includeArchived ? 'h-8 rounded-v2-sm bg-v2-primary px-3 text-sm font-medium text-white' : 'h-8 rounded-v2-sm px-3 text-sm text-v2-muted hover:bg-v2-surface-hover'}>活动</button><button onClick={() => setIncludeArchived(true)} className={includeArchived ? 'h-8 rounded-v2-sm bg-v2-primary px-3 text-sm font-medium text-white' : 'h-8 rounded-v2-sm px-3 text-sm text-v2-muted hover:bg-v2-surface-hover'}>已归档</button></div>{canCreate && !includeArchived && <Button onClick={() => setShowCreate(true)}><FilePlus2 className="mr-1.5 h-4 w-4" />新建布局</Button>}</div>
    <div className="relative max-w-sm"><Search className="absolute left-3 top-2.5 h-4 w-4 text-v2-muted" /><Input className="pl-9" placeholder="搜索布局名称" value={keyword} onChange={(event) => setKeyword(event.target.value)} /></div>
    {visible.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{visible.map((layout) => <article key={layout.layoutId} data-layout-id={layout.layoutId} className="group flex border border-v2-border bg-v2-surface transition-colors hover:bg-v2-surface-hover">{layout.status === 'ACTIVE' ? <Link href={`/cmdb/spatial/rooms/${layout.roomInstanceId}`} className="min-w-0 flex-1 p-4"><LayoutSummary layout={layout} /></Link> : <div className="min-w-0 flex-1 p-4"><LayoutSummary layout={layout} /></div>}{canPublish && <div className="p-2">{layout.status === 'ACTIVE' ? <Button variant="ghost" size="icon" title={`归档 ${layout.name}`} aria-label={`归档 ${layout.name}`} onClick={() => setArchiving(layout)}><Archive className="h-4 w-4" /></Button> : <Button variant="ghost" size="icon" title={`恢复 ${layout.name}`} aria-label={`恢复 ${layout.name}`} onClick={() => setRestoring(layout)}><RotateCcw className="h-4 w-4" /></Button>}</div>}</article>)}</div> : <div className="border border-dashed border-v2-border py-20 text-center"><Building2 className="mx-auto h-8 w-8 text-v2-muted" /><p className="mt-3 text-sm text-v2-muted">{includeArchived ? '暂无已归档布局' : '暂无空间布局'}</p>{canCreate && !includeArchived && <Button className="mt-4" variant="outline" onClick={() => setShowCreate(true)}>创建首个布局</Button>}</div>}
    {showCreate && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-v2-md border border-v2-border bg-v2-surface p-5 shadow-v2-lg"><h2 className="text-base font-semibold text-v2-fg">新建机房布局</h2><p className="mt-1 text-sm text-v2-muted">选择一个尚未配置布局的机房，系统会创建空草稿。</p><label className="mt-4 block text-sm font-medium" htmlFor="spatial-room-select">机房</label><select id="spatial-room-select" className="mt-2 h-9 w-full rounded-v2-sm border border-v2-border bg-v2-surface px-2 text-sm" value={roomId} onChange={(event) => setRoomId(event.target.value)} disabled={!availableRooms.length}><option value="">{availableRooms.length ? '选择机房' : '暂无可配置机房'}</option>{availableRooms.map((room) => <option key={room.roomInstanceId} value={room.roomInstanceId}>{room.name}</option>)}</select>{!availableRooms.length && <p className="mt-2 text-sm text-v2-muted">所有可见机房均已有活动布局；请先归档不再使用的布局，或在 CMDB 创建机房 CI。</p>}{create.error && <p className="mt-2 text-sm text-v2-danger">{getApiErrorMessage(create.error, '创建失败')}</p>}<div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={() => setShowCreate(false)}>取消</Button><Button disabled={!roomId || create.isPending} onClick={() => create.mutate()}>{create.isPending ? '创建中...' : '创建并编辑'}</Button></div></div></div>}
    {archiving && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div role="dialog" aria-modal="true" aria-labelledby="spatial-archive-title" className="w-full max-w-md rounded-v2-md border border-v2-border bg-v2-surface p-5 shadow-v2-lg"><h2 id="spatial-archive-title" className="text-base font-semibold text-v2-fg">归档空间布局</h2><p className="mt-2 text-sm text-v2-muted">归档后，该布局不再出现在活动机房列表中。已发布版本、历史记录和审计证据会保留，且不会删除任何 CI、关系或参考图。</p>{archive.error && <p className="mt-2 text-sm text-v2-danger">{getApiErrorMessage(archive.error, '归档失败')}</p>}<div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={() => setArchiving(null)}>取消</Button><Button variant="destructive" disabled={archive.isPending} onClick={() => archive.mutate(archiving.layoutId)}>{archive.isPending ? '归档中...' : '确认归档'}</Button></div></div></div>}
    {restoring && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div role="dialog" aria-modal="true" aria-labelledby="spatial-restore-active-title" className="w-full max-w-md rounded-v2-md border border-v2-border bg-v2-surface p-5 shadow-v2-lg"><h2 id="spatial-restore-active-title" className="text-base font-semibold text-v2-fg">恢复空间布局</h2><p className="mt-2 text-sm text-v2-muted">恢复后，该布局会重新成为机房的活动布局。若该机房已被其他活动布局占用，系统会拒绝恢复并保留当前归档状态。</p>{restore.error && <p className="mt-2 text-sm text-v2-danger">{getApiErrorMessage(restore.error, '恢复失败')}</p>}<div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={() => setRestoring(null)}>取消</Button><Button disabled={restore.isPending} onClick={() => restore.mutate(restoring.layoutId)}>{restore.isPending ? '恢复中...' : '确认恢复'}</Button></div></div></div>}
  </div>
}

function LayoutSummary({ layout }: { layout: SpatialLayoutSummary }) { return <div className="flex items-start gap-3"><div className="mt-0.5 rounded-v2-sm bg-v2-surface-soft p-2 text-v2-primary"><Map className="h-5 w-5" /></div><div className="min-w-0"><p className="truncate font-semibold text-v2-fg">{layout.name}</p><p className="mt-1 text-xs text-v2-muted">机房 #{layout.roomInstanceId}</p><p className="mt-3 text-xs text-v2-muted">{layout.status === 'ARCHIVED' ? '已归档' : layout.publishedVersionId ? '已发布' : '草稿未发布'}</p></div></div> }
